MICRO_EVENT_LIBRARY = {
    "smirk_left": {
        "kind": "smirk_left",
        "durationMs": 520,
        "patch": {"mouthForm": 0.42, "eyeLSmile": 0.66},
        "returnToBase": True,
    },
    "surprised_pop": {
        "kind": "surprised_pop",
        "durationMs": 320,
        "patch": {"eyeLOpen": 1.14, "eyeROpen": 1.14, "browLY": 0.28, "browRY": 0.28},
        "returnToBase": True,
    },
    "smirk_right": {
        "kind": "smirk_right",
        "durationMs": 520,
        "patch": {"mouthForm": 0.42, "eyeRSmile": 0.66},
        "returnToBase": True,
    },
    "wink_left": {
        "kind": "wink_left",
        "durationMs": 240,
        "patch": {"eyeLOpen": 0.02, "blushLevel": 0.12},
        "returnToBase": True,
    },
    "wink_right": {
        "kind": "wink_right",
        "durationMs": 240,
        "patch": {"eyeROpen": 0.02, "blushLevel": 0.12},
        "returnToBase": True,
    },
    "goofy_eye_cross_bias": {
        "kind": "goofy_eye_cross_bias",
        "durationMs": 380,
        "patch": {"eyeLOpen": 0.58, "eyeROpen": 0.94, "browLAngle": 0.18, "mouthForm": 0.10},
        "returnToBase": True,
    },
    "uneven_brow_pop": {
        "kind": "uneven_brow_pop",
        "durationMs": 300,
        "patch": {"browLY": 0.28, "browRY": 0.04, "browLAngle": 0.14},
        "returnToBase": True,
    },
    "gloom_drop": {
        "kind": "gloom_drop",
        "durationMs": 500,
        "patch": {"eyeLOpen": 0.55, "eyeROpen": 0.55, "browLY": -0.16, "browRY": -0.16, "mouthForm": -0.08, "blushLevel": -0.15},
        "returnToBase": True,
    },
    "tense_squeeze": {
        "kind": "tense_squeeze",
        "durationMs": 400,
        "patch": {"eyeLOpen": 0.62, "eyeROpen": 0.62, "browLAngle": -0.12, "browRAngle": 0.12, "browLX": 0.10, "browRX": -0.10, "blushLevel": -0.08},
        "returnToBase": True,
    },
    "shock_pop": {
        "kind": "shock_pop",
        "durationMs": 200,
        "patch": {"eyeLOpen": 1.25, "eyeROpen": 1.25, "browLY": 0.32, "browRY": 0.32, "mouthForm": 0.14},
        "returnToBase": True,
    },
    "volatile_twitch": {
        "kind": "volatile_twitch",
        "durationMs": 280,
        "patch": {"eyeLOpen": 0.60, "eyeROpen": 1.02, "browLAngle": 0.10, "browRAngle": -0.14, "mouthForm": 0.06},
        "returnToBase": True,
    },
    "meltdown_warp": {
        "kind": "meltdown_warp",
        "durationMs": 450,
        "patch": {"eyeLOpen": 0.40, "eyeROpen": 1.15, "browLAngle": 0.35, "browRAngle": 0.10, "mouthForm": -0.12, "browLForm": -0.20, "blushLevel": 0.08},
        "returnToBase": True,
    },
    "awkward_freeze": {
        "kind": "awkward_freeze",
        "durationMs": 600,
        "patch": {"eyeLOpen": 0.90, "eyeROpen": 1.0, "browLY": 0.06, "browRY": 0.10, "mouthForm": 0.02, "blushLevel": 0.10},
        "returnToBase": True,
    },
    "happy_smile_pulse": {
        "kind": "happy_smile_pulse",
        "durationMs": 640,
        "fadeInMs": 160,
        "fadeOutMs": 240,
        "patch": {"mouthForm": 0.36, "eyeLSmile": 0.54, "eyeRSmile": 0.48, "blushLevel": 0.08, "breathLevel": 0.72},
        "returnToBase": True,
    },
    "happy_brow_lift": {
        "kind": "happy_brow_lift",
        "durationMs": 560,
        "fadeInMs": 140,
        "fadeOutMs": 220,
        "patch": {"browLY": 0.22, "browRY": 0.18, "browLAngle": 0.10, "browRAngle": -0.08, "eyeLSmile": 0.42},
        "returnToBase": True,
    },
    "happy_eye_smile_right": {
        "kind": "happy_eye_smile_right",
        "durationMs": 620,
        "fadeInMs": 160,
        "fadeOutMs": 240,
        "patch": {"eyeRSmile": 0.58, "eyeROpen": 0.78, "mouthForm": 0.34, "physicsImpulse": 0.58},
        "returnToBase": True,
    },
    "playful_brow_spark": {
        "kind": "playful_brow_spark",
        "durationMs": 520,
        "fadeInMs": 130,
        "fadeOutMs": 210,
        "patch": {"eyeSync": False, "browLY": 0.26, "browRY": -0.02, "browLAngle": 0.20, "browRAngle": -0.12, "browLX": -0.08, "browRX": 0.06},
        "returnToBase": True,
    },
    "shy_blush_pulse": {
        "kind": "shy_blush_pulse",
        "durationMs": 760,
        "fadeInMs": 180,
        "fadeOutMs": 300,
        "patch": {"blushLevel": 0.62, "eyeLOpen": 0.72, "eyeROpen": 0.76, "mouthForm": 0.18, "breathLevel": 0.66},
        "returnToBase": True,
    },
    "shy_peek_left": {
        "kind": "shy_peek_left",
        "durationMs": 680,
        "fadeInMs": 180,
        "fadeOutMs": 260,
        "patch": {"eyeSync": False, "eyeLOpen": 0.82, "eyeROpen": 0.96, "browLY": -0.06, "browRY": 0.10, "browLAngle": -0.12, "browRAngle": 0.08, "browLX": 0.08, "browRX": -0.06},
        "returnToBase": True,
    },
    "angry_brow_press": {
        "kind": "angry_brow_press",
        "durationMs": 620,
        "fadeInMs": 120,
        "fadeOutMs": 240,
        "patch": {"browLY": -0.18, "browRY": -0.14, "browLAngle": 0.48, "browRAngle": -0.44, "browLForm": -0.34, "browRForm": -0.28, "browLX": 0.22, "browRX": -0.20, "blushLevel": -0.45},
        "returnToBase": True,
    },
    "angry_eye_narrow": {
        "kind": "angry_eye_narrow",
        "durationMs": 560,
        "fadeInMs": 120,
        "fadeOutMs": 220,
        "patch": {"eyeLOpen": 0.56, "eyeROpen": 0.62, "browLAngle": 0.42, "browRAngle": -0.38, "mouthForm": -0.22, "blushLevel": -0.50, "physicsImpulse": 0.58},
        "returnToBase": True,
    },
    "angry_stare_flash": {
        "kind": "angry_stare_flash",
        "durationMs": 460,
        "fadeInMs": 120,
        "fadeOutMs": 200,
        "patch": {"eyeLOpen": 1.16, "eyeROpen": 1.14, "browLY": -0.06, "browRY": -0.06, "browLAngle": 0.50, "browRAngle": -0.50, "mouthForm": -0.18, "blushLevel": -0.42},
        "returnToBase": True,
    },
    "sad_brow_waver": {
        "kind": "sad_brow_waver",
        "durationMs": 760,
        "fadeInMs": 190,
        "fadeOutMs": 300,
        "patch": {"browLY": -0.18, "browRY": -0.16, "browLAngle": -0.34, "browRAngle": 0.32, "browLX": 0.14, "browRX": -0.12, "mouthForm": -0.34, "blushLevel": -0.42},
        "returnToBase": True,
    },
    "sad_eye_sink": {
        "kind": "sad_eye_sink",
        "durationMs": 820,
        "fadeInMs": 200,
        "fadeOutMs": 320,
        "patch": {"eyeLOpen": 0.54, "eyeROpen": 0.56, "eyeLSmile": 0.02, "eyeRSmile": 0.02, "mouthForm": -0.42, "blushLevel": -0.55, "breathLevel": 0.42},
        "returnToBase": True,
    },
    "gloomy_flat_hold": {
        "kind": "gloomy_flat_hold",
        "durationMs": 880,
        "fadeInMs": 220,
        "fadeOutMs": 320,
        "patch": {"eyeLOpen": 0.50, "eyeROpen": 0.52, "browLY": -0.12, "browRY": -0.12, "mouthForm": -0.16, "blushLevel": -0.48},
        "returnToBase": True,
    },
    "surprised_eye_pop": {
        "kind": "surprised_eye_pop",
        "durationMs": 420,
        "fadeInMs": 120,
        "fadeOutMs": 220,
        "patch": {"eyeLOpen": 1.22, "eyeROpen": 1.22, "browLY": 0.34, "browRY": 0.34, "mouthForm": 0.20, "breathLevel": 0.78, "physicsImpulse": 0.62},
        "returnToBase": True,
    },
    "conflicted_brow_tilt": {
        "kind": "conflicted_brow_tilt",
        "durationMs": 680,
        "fadeInMs": 170,
        "fadeOutMs": 260,
        "patch": {"eyeSync": False, "eyeLOpen": 0.86, "eyeROpen": 1.06, "browLY": 0.14, "browRY": -0.10, "browLAngle": 0.26, "browRAngle": -0.20, "mouthForm": -0.04, "blushLevel": -0.10},
        "returnToBase": True,
    },
    "brow_micro_dual_lift": {
        "kind": "brow_micro_dual_lift",
        "durationMs": 720,
        "fadeInMs": 150,
        "fadeOutMs": 260,
        "patch": {"eyeSync": True, "eyeLOpen": 1.04, "eyeROpen": 1.04, "browLY": 0.34, "browRY": 0.34, "browLAngle": 0.10, "browRAngle": -0.10, "browLForm": 0.16, "browRForm": 0.16},
        "returnToBase": True,
    },
    "brow_micro_curve_smile": {
        "kind": "brow_micro_curve_smile",
        "durationMs": 980,
        "fadeInMs": 190,
        "fadeOutMs": 320,
        "patch": {"eyeSync": True, "eyeLOpen": 0.78, "eyeROpen": 0.78, "eyeLSmile": 0.70, "eyeRSmile": 0.70, "browLY": 0.14, "browRY": 0.14, "browLAngle": -0.04, "browRAngle": 0.04, "browLForm": 0.42, "browRForm": 0.42, "mouthForm": 0.34},
        "returnToBase": True,
    },
    "brow_micro_understand_lift": {
        "kind": "brow_micro_understand_lift",
        "durationMs": 1180,
        "fadeInMs": 210,
        "fadeOutMs": 340,
        "patch": {"eyeSync": True, "eyeLOpen": 1.02, "eyeROpen": 1.02, "eyeLSmile": 0.24, "eyeRSmile": 0.24, "browLY": 0.24, "browRY": 0.24, "browLAngle": 0.06, "browRAngle": -0.06, "browLForm": 0.28, "browRForm": 0.28, "mouthForm": 0.14},
        "returnToBase": True,
    },
    "brow_micro_surprise_arc": {
        "kind": "brow_micro_surprise_arc",
        "durationMs": 640,
        "fadeInMs": 120,
        "fadeOutMs": 240,
        "patch": {"eyeSync": True, "eyeLOpen": 1.20, "eyeROpen": 1.20, "browLY": 0.42, "browRY": 0.42, "browLAngle": 0.16, "browRAngle": -0.16, "browLForm": 0.24, "browRForm": 0.24, "mouthForm": 0.18, "physicsImpulse": 0.54},
        "returnToBase": True,
    },
    "brow_micro_soft_question": {
        "kind": "brow_micro_soft_question",
        "durationMs": 1100,
        "fadeInMs": 200,
        "fadeOutMs": 320,
        "patch": {"eyeSync": False, "eyeLOpen": 0.96, "eyeROpen": 1.06, "browLY": 0.26, "browRY": 0.04, "browLAngle": 0.18, "browRAngle": -0.06, "browLForm": 0.18, "browRForm": 0.04, "browLX": -0.06, "browRX": 0.04, "mouthForm": 0.08},
        "returnToBase": True,
    },
    "brow_micro_inner_worry": {
        "kind": "brow_micro_inner_worry",
        "durationMs": 1040,
        "fadeInMs": 220,
        "fadeOutMs": 340,
        "patch": {"eyeSync": True, "eyeLOpen": 0.70, "eyeROpen": 0.70, "browLY": -0.12, "browRY": -0.12, "browLAngle": -0.30, "browRAngle": 0.30, "browLForm": -0.22, "browRForm": -0.22, "browLX": 0.12, "browRX": -0.12, "mouthForm": -0.22, "blushLevel": -0.38},
        "returnToBase": True,
    },
}


SPEAKING_SEQUENCE_POOLS = {
    "happy": ["happy_smile_pulse", "brow_micro_curve_smile", "brow_micro_dual_lift", "brow_micro_understand_lift", "happy_brow_lift", "happy_eye_smile_right", "uneven_brow_pop"],
    "playful": ["playful_brow_spark", "brow_micro_soft_question", "brow_micro_dual_lift", "happy_smile_pulse", "smirk_left", "smirk_right"],
    "teasing": ["playful_brow_spark", "brow_micro_soft_question", "smirk_left", "happy_brow_lift", "smirk_right"],
    "shy": ["shy_blush_pulse", "brow_micro_curve_smile", "shy_peek_left", "brow_micro_inner_worry", "awkward_freeze", "happy_smile_pulse"],
    "angry": ["angry_brow_press", "angry_eye_narrow", "angry_stare_flash", "tense_squeeze"],
    "sad": ["sad_brow_waver", "brow_micro_inner_worry", "sad_eye_sink", "tense_squeeze", "gloomy_flat_hold"],
    "gloomy": ["gloomy_flat_hold", "brow_micro_inner_worry", "sad_eye_sink", "gloom_drop", "sad_brow_waver"],
    "surprised": ["brow_micro_surprise_arc", "surprised_eye_pop", "brow_micro_dual_lift", "shock_pop", "brow_micro_understand_lift"],
    "conflicted": ["conflicted_brow_tilt", "brow_micro_soft_question", "volatile_twitch", "tense_squeeze", "brow_micro_inner_worry"],
    "neutral": ["brow_micro_understand_lift", "brow_micro_dual_lift", "happy_brow_lift", "happy_smile_pulse", "conflicted_brow_tilt"],
}


SEQUENCE_LIBRARY = {
    "bright_talk_bounce": [
        {
            "kind": "bright_sway_left",
            "durationMs": 900,
            "fadeInMs": 180,
            "fadeOutMs": 260,
            "patch": {
                "mouthForm": 0.42,
                "eyeLSmile": 0.68,
                "breathLevel": 0.86,
                "physicsImpulse": 0.92,
            },
            "returnToBase": True,
        },
        {
            "kind": "bright_sway_right",
            "durationMs": 900,
            "fadeInMs": 180,
            "fadeOutMs": 260,
            "patch": {
                "mouthForm": 0.42,
                "eyeRSmile": 0.68,
                "breathLevel": 0.84,
                "physicsImpulse": 0.90,
            },
            "returnToBase": True,
        },
    ],
    "pause_then_goofy": [
        {"kind": "awkward_freeze", "durationMs": 300, "patch": {"mouthForm": 0.02, "eyeLOpen": 0.88, "eyeROpen": 0.92, "blushLevel": 0.10}, "returnToBase": True},
        {"kind": "goofy_eye_cross_bias", "durationMs": 380, "patch": {"eyeLOpen": 0.58, "eyeROpen": 0.94, "browLAngle": 0.18}, "returnToBase": True},
    ],
    "smirk_then_flat": [
        {"kind": "smirk_left", "durationMs": 420, "patch": {"mouthForm": 0.38, "eyeLSmile": 0.55}, "returnToBase": True},
        {"kind": "awkward_freeze", "durationMs": 250, "patch": {"mouthForm": 0.04, "eyeLSmile": 0.10, "eyeRSmile": 0.10, "blushLevel": 0.10}, "returnToBase": True},
    ],
    "drop_then_gloom": [
        {"kind": "shock_pop", "durationMs": 180, "patch": {"eyeLOpen": 1.10, "eyeROpen": 1.10, "browLY": 0.20, "browRY": 0.20}, "returnToBase": True},
        {"kind": "gloom_drop", "durationMs": 500, "patch": {"eyeLOpen": 0.55, "eyeROpen": 0.55, "browLY": -0.16, "browRY": -0.16, "mouthForm": -0.08, "blushLevel": -0.15}, "returnToBase": True},
    ],
    "tense_then_break": [
        {"kind": "tense_squeeze", "durationMs": 400, "patch": {"eyeLOpen": 0.62, "eyeROpen": 0.62, "browLAngle": -0.12, "browRAngle": 0.12, "browLX": 0.10, "browRX": -0.10, "blushLevel": -0.08}, "returnToBase": True},
        {"kind": "shock_pop", "durationMs": 180, "patch": {"eyeLOpen": 1.15, "eyeROpen": 1.15}, "returnToBase": True},
    ],
    "burst_then_unstable": [
        {"kind": "shock_pop", "durationMs": 200, "patch": {"eyeLOpen": 1.25, "eyeROpen": 1.25, "browLY": 0.32, "browRY": 0.32, "mouthForm": 0.14}, "returnToBase": True},
        {"kind": "volatile_twitch", "durationMs": 280, "patch": {"eyeLOpen": 0.60, "eyeROpen": 1.02, "browLAngle": 0.10, "browRAngle": -0.14, "mouthForm": 0.06}, "returnToBase": True},
    ],
}
