"""Idle plan data used by the expression compiler."""

IDLE_PLAN_LOOP_EVENTS = {
    "happy_idle": [
        {
            "kind": "happy_idle_warm_lift",
            "durationMs": 680,
            "patch": {
                "bodyAngleX": 0.06,
                "bodyAngleY": 0.04,
                "bodyAngleZ": -0.04,
                "breathLevel": 0.58,
                "physicsImpulse": 0.30,
                "mouthForm": 0.34,
                "eyeLOpen": 0.82,
                "eyeROpen": 0.84,
                "eyeLSmile": 0.56,
                "eyeRSmile": 0.52,
                "browLY": 0.08,
                "browRY": 0.06,
                "blushLevel": 0.08,
            },
            "returnToBase": True,
        },
    ],
    "crying_idle": [
        {
            "kind": "crying_idle_tremble_breath",
            "durationMs": 1080,
            "patch": {
                "bodyAngleX": -0.10,
                "bodyAngleY": -0.04,
                "bodyAngleZ": 0.02,
                "breathLevel": 0.30,
                "physicsImpulse": 0.12,
                "eyeLOpen": 0.48,
                "eyeROpen": 0.50,
                "mouthForm": -0.42,
                "browLY": -0.22,
                "browRY": -0.20,
                "browLAngle": -0.34,
                "browRAngle": 0.34,
                "blushLevel": -0.65,
            },
            "returnToBase": True,
        },
    ],
    "angry_glare_idle": [
        {
            "kind": "angry_idle_glare_lock",
            "durationMs": 760,
            "patch": {
                "bodyAngleX": 0.10,
                "bodyAngleY": -0.07,
                "bodyAngleZ": 0.10,
                "breathLevel": 0.52,
                "physicsImpulse": 0.52,
                "eyeLOpen": 1.20,
                "eyeROpen": 1.20,
                "mouthForm": -0.26,
                "browLY": -0.24,
                "browRY": -0.24,
                "browLAngle": 0.78,
                "browRAngle": -0.78,
                "browLForm": -0.42,
                "browRForm": -0.42,
                "blushLevel": -0.70,
            },
            "returnToBase": True,
        },
    ],
    "shy_idle": [
        {
            "kind": "shy_idle_side_peek",
            "durationMs": 640,
            "patch": {
                "bodyAngleX": -0.06,
                "bodyAngleY": 0.09,
                "bodyAngleZ": -0.09,
                "breathLevel": 0.50,
                "physicsImpulse": 0.26,
                "eyeLOpen": 0.58,
                "eyeROpen": 0.88,
                "mouthForm": 0.06,
                "eyeLSmile": 0.08,
                "eyeRSmile": 0.20,
                "browLY": 0.02,
                "browRY": 0.12,
                "browLAngle": -0.10,
                "browRAngle": 0.16,
                "browLX": -0.10,
                "browRX": 0.08,
                "blushLevel": 0.42,
            },
            "returnToBase": True,
        },
    ],
    "gloomy_idle": [
        {
            "kind": "gloomy_idle_slow_sink",
            "durationMs": 1180,
            "patch": {
                "bodyAngleX": -0.08,
                "bodyAngleY": -0.06,
                "bodyAngleZ": 0.02,
                "breathLevel": 0.24,
                "physicsImpulse": 0.08,
                "eyeLOpen": 0.46,
                "eyeROpen": 0.48,
                "mouthForm": -0.22,
                "browLY": -0.30,
                "browRY": -0.30,
                "browLAngle": -0.20,
                "browRAngle": 0.20,
                "browLForm": -0.18,
                "browRForm": -0.18,
                "blushLevel": -0.28,
            },
            "returnToBase": True,
        },
    ],
}


IDLE_PLAN_LOOP_INTERVAL_MS = {
    "happy_idle": 2200,
    "crying_idle": 3600,
    "angry_glare_idle": 3000,
    "shy_idle": 2400,
    "gloomy_idle": 4200,
}


AMBIENT_IDLE_STATE_ORDER = [
    "ambient_idle_breath",
    "ambient_idle_look_around",
    "ambient_idle_active_shift",
]

AMBIENT_IDLE_ENTER_AFTER_MS = {
    "min": 9000,
    "max": 14000,
}

AMBIENT_IDLE_SWITCH_INTERVAL_MS = {
    "min": 5200,
    "max": 9200,
}

AMBIENT_IDLE_STATE_TEMPLATES = {
    "ambient_idle_breath": {
        "params": {
            "headIntensity": 0.03,
            "bodyAngleX": 0.00,
            "bodyAngleY": -0.02,
            "bodyAngleZ": 0.00,
            "breathLevel": 0.38,
            "physicsImpulse": 0.10,
            "blushLevel": 0.02,
            "eyeSync": True,
            "eyeLOpen": 0.78,
            "eyeROpen": 0.80,
            "mouthForm": 0.02,
            "browLY": -0.02,
            "browRY": -0.02,
            "browLAngle": 0.02,
            "browRAngle": -0.02,
            "browLForm": 0.01,
            "browRForm": 0.01,
            "eyeLSmile": 0.04,
            "eyeRSmile": 0.04,
            "browLX": 0.00,
            "browRX": 0.00,
        },
        "jitter": {
            "bodyAngleX": 0.03,
            "bodyAngleY": 0.03,
            "bodyAngleZ": 0.03,
            "breathLevel": 0.05,
            "physicsImpulse": 0.03,
            "blushLevel": 0.05,
            "eyeLOpen": 0.05,
            "eyeROpen": 0.05,
            "mouthForm": 0.04,
            "browLY": 0.04,
            "browRY": 0.04,
            "browLAngle": 0.05,
            "browRAngle": 0.05,
            "browLForm": 0.04,
            "browRForm": 0.04,
            "eyeLSmile": 0.04,
            "eyeRSmile": 0.04,
            "browLX": 0.03,
            "browRX": 0.03,
        },
    },
    "ambient_idle_look_around": {
        "params": {
            "headIntensity": 0.04,
            "bodyAngleX": 0.05,
            "bodyAngleY": 0.06,
            "bodyAngleZ": -0.06,
            "breathLevel": 0.46,
            "physicsImpulse": 0.24,
            "blushLevel": 0.00,
            "eyeSync": False,
            "eyeLOpen": 0.88,
            "eyeROpen": 0.74,
            "mouthForm": 0.00,
            "browLY": 0.05,
            "browRY": -0.02,
            "browLAngle": -0.10,
            "browRAngle": 0.12,
            "browLForm": 0.00,
            "browRForm": 0.00,
            "eyeLSmile": 0.02,
            "eyeRSmile": 0.00,
            "browLX": -0.10,
            "browRX": 0.08,
        },
        "jitter": {
            "headIntensity": 0.02,
            "bodyAngleX": 0.04,
            "bodyAngleY": 0.04,
            "bodyAngleZ": 0.04,
            "breathLevel": 0.06,
            "physicsImpulse": 0.05,
            "blushLevel": 0.04,
            "eyeLOpen": 0.06,
            "eyeROpen": 0.06,
            "mouthForm": 0.03,
            "browLY": 0.05,
            "browRY": 0.05,
            "browLAngle": 0.06,
            "browRAngle": 0.06,
            "eyeLSmile": 0.03,
            "eyeRSmile": 0.03,
            "browLX": 0.04,
            "browRX": 0.04,
        },
    },
    "ambient_idle_active_shift": {
        "params": {
            "headIntensity": 0.08,
            "bodyAngleX": 0.07,
            "bodyAngleY": 0.04,
            "bodyAngleZ": -0.05,
            "breathLevel": 0.56,
            "physicsImpulse": 0.34,
            "blushLevel": 0.03,
            "eyeSync": True,
            "eyeLOpen": 0.92,
            "eyeROpen": 0.90,
            "mouthForm": 0.08,
            "browLY": 0.04,
            "browRY": 0.02,
            "browLAngle": 0.04,
            "browRAngle": -0.04,
            "browLForm": 0.02,
            "browRForm": 0.02,
            "eyeLSmile": 0.10,
            "eyeRSmile": 0.08,
            "browLX": 0.03,
            "browRX": -0.03,
        },
        "jitter": {
            "headIntensity": 0.02,
            "bodyAngleX": 0.04,
            "bodyAngleY": 0.04,
            "bodyAngleZ": 0.04,
            "breathLevel": 0.07,
            "physicsImpulse": 0.05,
            "blushLevel": 0.05,
            "eyeLOpen": 0.05,
            "eyeROpen": 0.05,
            "mouthForm": 0.05,
            "browLY": 0.05,
            "browRY": 0.05,
            "browLAngle": 0.05,
            "browRAngle": 0.05,
            "browLForm": 0.04,
            "browRForm": 0.04,
            "eyeLSmile": 0.04,
            "eyeRSmile": 0.04,
            "browLX": 0.04,
            "browRX": 0.04,
        },
    },
}


IDLE_PLAN_SETTLE_PATCHES = {
    "happy_idle": {
        "headIntensity": 0.05,
        "bodyAngleX": 0.02,
        "bodyAngleY": 0.01,
        "bodyAngleZ": -0.01,
        "breathLevel": 0.42,
        "physicsImpulse": 0.14,
        "mouthForm": 0.26,
        "eyeLOpen": 0.86,
        "eyeROpen": 0.86,
        "eyeSync": True,
        "eyeLSmile": 0.44,
        "eyeRSmile": 0.42,
        "browLY": 0.04,
        "browRY": 0.04,
        "browLAngle": 0.04,
        "browRAngle": -0.04,
        "blushLevel": 0.06,
    },
    "crying_idle": {
        "headIntensity": 0.01,
        "bodyAngleX": -0.12,
        "bodyAngleY": -0.04,
        "bodyAngleZ": 0.02,
        "breathLevel": 0.26,
        "physicsImpulse": 0.08,
        "mouthForm": -0.34,
        "eyeLOpen": 0.56,
        "eyeROpen": 0.58,
        "eyeSync": True,
        "eyeLSmile": 0.0,
        "eyeRSmile": 0.0,
        "browLY": -0.18,
        "browRY": -0.18,
        "browLAngle": -0.30,
        "browRAngle": 0.30,
        "browLForm": -0.22,
        "browRForm": -0.22,
        "browLX": 0.08,
        "browRX": -0.08,
        "blushLevel": -0.55,
    },
    "angry_glare_idle": {
        "headIntensity": 0.04,
        "bodyAngleX": 0.06,
        "bodyAngleY": -0.05,
        "bodyAngleZ": 0.06,
        "breathLevel": 0.38,
        "physicsImpulse": 0.28,
        "mouthForm": -0.22,
        "eyeLOpen": 1.14,
        "eyeROpen": 1.14,
        "eyeSync": True,
        "eyeLSmile": 0.0,
        "eyeRSmile": 0.0,
        "browLY": -0.20,
        "browRY": -0.20,
        "browLAngle": 0.62,
        "browRAngle": -0.62,
        "browLForm": -0.36,
        "browRForm": -0.36,
        "browLX": 0.12,
        "browRX": -0.12,
        "blushLevel": -0.60,
    },
    "shy_idle": {
        "headIntensity": 0.03,
        "bodyAngleX": -0.04,
        "bodyAngleY": 0.04,
        "bodyAngleZ": -0.06,
        "breathLevel": 0.36,
        "physicsImpulse": 0.12,
        "mouthForm": 0.08,
        "eyeLOpen": 0.62,
        "eyeROpen": 0.84,
        "eyeSync": False,
        "eyeLSmile": 0.10,
        "eyeRSmile": 0.22,
        "browLY": 0.02,
        "browRY": 0.10,
        "browLAngle": -0.08,
        "browRAngle": 0.12,
        "browLX": -0.08,
        "browRX": 0.08,
        "blushLevel": 0.34,
    },
    "gloomy_idle": {
        "headIntensity": 0.01,
        "bodyAngleX": -0.08,
        "bodyAngleY": -0.06,
        "bodyAngleZ": 0.01,
        "breathLevel": 0.20,
        "physicsImpulse": 0.06,
        "mouthForm": -0.18,
        "eyeLOpen": 0.54,
        "eyeROpen": 0.56,
        "eyeSync": True,
        "eyeLSmile": 0.0,
        "eyeRSmile": 0.0,
        "browLY": -0.26,
        "browRY": -0.26,
        "browLAngle": -0.18,
        "browRAngle": 0.18,
        "browLForm": -0.16,
        "browRForm": -0.16,
        "browLX": 0.04,
        "browRX": -0.04,
        "blushLevel": -0.28,
    },
}

