PRESET_VARIATION_RULES = {
    "calm_soft": {},
    "playful_smirk": {},
    "shy_tucked": {},
    "surprised_open": {},
}


BASE_POSE_PRESETS = {
    "calm_soft": {
        "mouthForm": 0.05,
        "eyeLOpen": 0.96,
        "eyeROpen": 0.96,
        "eyeSync": True,
        "browLY": 0.02,
        "browRY": 0.02,
        "browLAngle": 0.02,
        "browRAngle": -0.02,
        "browLForm": 0.0,
        "browRForm": 0.0,
        "eyeLSmile": 0.08,
        "eyeRSmile": 0.08,
        "browLX": 0.0,
        "browRX": 0.0,
        "headIntensity": 0.15,
        "blushLevel": 0.0,
    },
    "playful_smirk": {
        "mouthForm": 0.24,
        "eyeLOpen": 0.84,
        "eyeROpen": 0.74,
        "eyeSync": False,
        "browLY": 0.12,
        "browRY": 0.04,
        "browLAngle": 0.20,
        "browRAngle": -0.06,
        "browLForm": 0.1,
        "browRForm": 0.02,
        "eyeLSmile": 0.42,
        "eyeRSmile": 0.14,
        "browLX": -0.08,
        "browRX": 0.04,
        "headIntensity": 0.28,
        "blushLevel": 0.05,
    },
    "shy_tucked": {
        "mouthForm": 0.10,
        "eyeLOpen": 0.78,
        "eyeROpen": 0.82,
        "eyeSync": False,
        "browLY": 0.08,
        "browRY": 0.02,
        "browLAngle": 0.10,
        "browRAngle": -0.04,
        "browLForm": 0.08,
        "browRForm": 0.03,
        "eyeLSmile": 0.18,
        "eyeRSmile": 0.10,
        "browLX": -0.04,
        "browRX": 0.02,
        "headIntensity": 0.18,
        "blushLevel": 0.18,
    },
    "surprised_open": {
        "mouthForm": 0.12,
        "eyeLOpen": 1.08,
        "eyeROpen": 1.08,
        "eyeSync": True,
        "browLY": 0.22,
        "browRY": 0.22,
        "browLAngle": 0.18,
        "browRAngle": -0.18,
        "browLForm": 0.02,
        "browRForm": 0.02,
        "eyeLSmile": 0.0,
        "eyeRSmile": 0.0,
        "browLX": 0.0,
        "browRX": 0.0,
        "headIntensity": 0.34,
        "blushLevel": 0.02,
    },
}
